### PR TITLE
Calculation and plotting of extinction curves

### PR DESCRIPTION
**Pull request by mdcleir**
I updated the merge function so that NaN values and low SNR regions are excluded.
The calc_ext.py script now only calculates the extinction curve and saves it to a fits file. The plot_ext.py does the plotting.

### CODE REVIEW

**Comment by mdcleir** [comment]
> Overall looks good.
> 
> Did you mean to include all the binary files? Eg. the eps, png, and pdf files? Not clear if these are needed unless they are in the docs (or plan to be).

These are output files of plot_spectra.py and plot_ext.py (if you use the --pdf etc. flags). I included them as "examples", but can take them out if you want.

**Comment by karllark** [comment]
Probably don't need them all.  Maybe just keep the png files as these are likely to be useful for the docs.

**Comment by mdcleir** [comment]
> Probably don't need them all. Maybe just keep the png files as these are likely to be useful for the docs.

Ok! I deleted the other files.

**Comment by karllark** [comment]
Great.  Merging.

**Pull request merged**
