### PR TITLE
Extinction curves measurements/plotting/documentation

### PR DESCRIPTION
**Pull request by mdecleir**
This PR includes the following updates/additions:
- Wrote a script to automatically create and plot extinction curves for all stars in the list.
- Adjusted some modules to be useable in other scripts.
- Fixed a RuntimeWarning when plotting.
- Fixed issue with two different LXD modes.
- Updated the documentation with other stars that have a full UV-MIR coverage.
- Deleted and added several data files to go with the updated documentation.
- Added functionality to plot all extinction curves in one figure, labeling the curves with the star name, and coloring them according to increasing extinction value.
- Updated workflow to normalize the extinction curve to A(V).
- Added functionality to zoom in on a certain wavelength region, updating the colors of the curves accordingly.

### CODE REVIEW

**Comment by karllark** [comment]
Great to see the updates.  Will carefully review in a little bit when I have more time.

Note that the tests are failing because this PR removes the data files they were using.  Can you either put those data files back or switch the simple tests to use the new data files you added?  The latter is probably the best solution - fewer files!

**Comment by mdecleir** [comment]
Problem: For some reason, the new .dat files in the data/ folder are not listed as untracked files when I do a git status. If I try to add them, I get the following error:

$ git add hd229238.dat 
The following paths are ignored by one of your .gitignore files:
measure_extinction/data/hd229238.dat
Use -f if you really want to add them.

I did not have this issue before, what does this mean?

**Comment by karllark** [comment]
Look at the .gitignore file and remove the *.dat.  That's my guess.  Probably was me adding this line to the .gitignore.  Sigh.

**Comment by mdecleir** [comment]
> There are test failures as some packages are not in the setup.cfg (see `install_requires` line in the `[options]` section). Can you add them? Looking at the travis test failures, there are at least three that I can see - `pandas`, `emcee`, and `astropy-pytest`. There might be more.

Ok, I will add them. However, I don't fully understand why this is. I am indeed using the pandas package. But the other two are not used in the new code... Also, why do the tests on my computer not fail?

**Comment by karllark** [comment]
The current travis errors are related to something in a different part of the code and some issue with the flake8 tests not working.   Both should be fixed in separate PRs.  Two issues for this are #47 and #48.

**Pull request merged**
