### PR TITLE
Plot tweaks

### PR DESCRIPTION
**Pull request by mdecleir**
This PR contains several changes to the plotting of spectra and extinction curves:
- Changed default plotting settings
- Added option to exclude certain bands from plotting instead of all bands or no bands

Other changes:
- Quadratically added 1 percent uncertainty to the SpeX spectra
- Small updates to masked windows of SpeX spectra

Some changes will be in conflict with the latest merge from PR #66 , so we will have to fix the conflicts first.

### CODE REVIEW

**Comment by mdecleir** [comment]
For some reason, it is only doing 1 test. Where did all the other tests go?

**Comment by mdecleir** [comment]
Looking at the conflicts, I don't really understand why they are indicated as conflicts. They are different keywords that we added separately, but these are independent from each other. We want to keep both keywords. How can we fix this?

**Comment by karllark** [comment]
> Looking at the conflicts, I don't really understand why they are indicated as conflicts. They are different keywords that we added separately, but these are independent from each other. We want to keep both keywords. How can we fix this?

The automated routine can't decide if the changes are in conflict or not.  They are in the same place in the code and have different names.  Hence it is kicking this back to the humans.  The solution is to rebase and manually include both changes.

**Comment by karllark** [comment]
> For some reason, it is only doing 1 test. Where did all the other tests go?

Only one test in being run as there are merge conflicts, hence it cannot run any of the other tests.

**Comment by mdecleir** [comment]
I merged the changes. This should solve the conflicts.

**Comment by mdecleir** [comment]
I clearly broke the code by merging the changes. I will try to fix this.

**Comment by karllark** [comment]
> I clearly broke the code by merging the changes. I will try to fix this.

Been there.  Did this last week.  ;-)

**Comment by mdecleir** [comment]
Issues have been fixed. Tests are successful now. This PR is ready to be reviewed.

**Review by karllark — APPROVED** [review]
Looks good to me.

**Pull request merged**
