### PR TITLE
fixing docs

### PR DESCRIPTION
**Pull request by mdcleir**

### CODE REVIEW

**Comment by mdcleir** [comment]
I fixed the "spectra" and "extinction" parts of the documentation, and corrected some typos/spelling mistakes. The "normalization" part still needs to be checked. I also fixed the test files.

**Comment by karllark** [comment]
Looks great.  The docs are still failing to build as there are two 'calc_elv' references in the normalization part.  Can you go ahead and change those to 'calc_elx' and then I think the docs will build?

**Comment by mdcleir** [comment]
> Looks great. The docs are still failing to build as there are two 'calc_elv' references in the normalization part. Can you go ahead and change those to 'calc_elx' and then I think the docs will build?

Done!

**Comment by karllark** [comment]
Great.  I'm going to merge.  The other travis failures are due to issues that I will try and fix myself (should be a quick to do I think).

**Pull request merged**
