### PR TITLE
Add more flexibility to plotting settings

### PR DESCRIPTION
**Pull request by mdecleir**
I added more flexibility to the plotting settings so that this repo is again compatible with the spex_nir_extinction repo, and can be used for future projects without having to change all the settings manually.

### CODE REVIEW

**Comment by mdecleir** [comment]
@karllark I am struggling with one of the plots. You added a `fig.tight_layout()` in `plot_ext.py`, which changes the outcome of the figure quite a bit. I have been searching for hours now, but cannot find a way to undo the tight_layout after the fact. It is a tricky function that does not just change space around the plot, but also changes axes labels, tick labels, thickness of the lines, etc... The only solution I could think of is to make it an optional parameter. I think these plotting functions start to have way too many parameters, but I could not find another solution for this particular case.

**Comment by karllark** [comment]
> @karllark I am struggling with one of the plots. You added a `fig.tight_layout()` in `plot_ext.py`, which changes the outcome of the figure quite a bit. I have been searching for hours now, but cannot find a way to undo the tight_layout after the fact. It is a tricky function that does not just change space around the plot, but also changes axes labels, tick labels, thickness of the lines, etc... The only solution I could think of is to make it an optional parameter. I think these plotting functions start to have way too many parameters, but I could not find another solution for this particular case.

I would be fine with removing the fig.tight_layout.  It can always be added in the calling code.

**Comment by mdecleir** [comment]
> > @karllark I am struggling with one of the plots. You added a `fig.tight_layout()` in `plot_ext.py`, which changes the outcome of the figure quite a bit. I have been searching for hours now, but cannot find a way to undo the tight_layout after the fact. It is a tricky function that does not just change space around the plot, but also changes axes labels, tick labels, thickness of the lines, etc... The only solution I could think of is to make it an optional parameter. I think these plotting functions start to have way too many parameters, but I could not find another solution for this particular case.
> 
> I would be fine with removing the fig.tight_layout. It can always be added in the calling code.

Ah yes, that is probably the better solution :) Thanks!

**Comment by mdecleir** [comment]
@karllark This PR is ready for review.

**Review by karllark — APPROVED** [review]
Looks good to me.

**Pull request merged**
