### PR TITLE
Loops

### PR DESCRIPTION
**Pull request by mdecleir**
I added a script to do all steps (merging, scaling and plotting) for all stars automatically. The other modules were changed as necessary. I also did 2 fixes. One fix is to avoid a recurring warning about invalid values when filtering regions with low SNR. The other fix is to prevent issues when the correction factor is None. This "None" was read as a string, and not as a NoneType, which caused errors when trying to scale the spectra.

### CODE REVIEW

**Comment by karllark** [comment]
Can you rename the main script to be more descriptive than "do_all_..."?  Something that describes what "all" is.

**Comment by karllark** [comment]
Why is a separate `corr_spex` function needed?  The correction factors are applied in the stardata.read_spex function (https://github.com/karllark/measure_extinction/blob/c80a98fc6d55ac93ceb059774ff2de914f76ee2e/measure_extinction/stardata.py#L696).

It looks like in your `do_all...` script that the SpeX correction factors will be applied twice as a result.

**Comment by mdecleir** [comment]
> Can you rename the main script to be more descriptive than "do_all_..."? Something that describes what "all" is.

The reason why the name is so vague is because I am not sure yet where I want to go with this script. At this moment it merges/bins the Spex spectra, calculates the scaling factor for the Spex spectra and plots all spectra (also IUE, IRS,...) for all stars. I am considering also adding the calculation of the extinction curve to this script, although this would require a way to link reddened stars to comparison stars automatically, so I am not sure yet if that will be feasible. For now, I changed the name to merge_scale_plot_all_stars_spex_spectra.py, although that is a bit long I think. Also "merge" is actually a wrong name in general for what the merge script is doing, as for the SpeX it is only re-writing the data in the correct format, and binning the wavelengths to get the required resolution... What are your thoughts about this?

**Comment by mdecleir** [comment]
> Why is a separate `corr_spex` function needed? The correction factors are applied in the stardata.read_spex function (
> 
> https://github.com/karllark/measure_extinction/blob/c80a98fc6d55ac93ceb059774ff2de914f76ee2e/measure_extinction/stardata.py#L696
> 
> ).
> It looks like in your `do_all...` script that the SpeX correction factors will be applied twice as a result.

The corr_spex function (in spex_corr.py) does not apply the correction factors. It reads the data, calculates the correction factor, and saves the factors in the .dat files. There was already another function called "calc_corfac" so I named this function corr_spex, but maybe I should rename it?

**Comment by karllark** [comment]
How about `calc_corrfac_spex`?  Longer and more descriptive names are never bad.

**Comment by karllark** [comment]
Maybe something like `process_all_spex_spectra` or `prepare_all_spex_spectra`?

**Comment by karllark** [comment]
I like the `prepare` now that I think about it as this is what this script is doing.

**Comment by mdecleir** [comment]
> I like the `prepare` now that I think about it as this is what this script is doing.

I like the prepare too! Renamed it again :)

**Comment by mdecleir** [comment]
> How about `calc_corrfac_spex`? Longer and more descriptive names are never bad.

I changed it to calc_save_corfac_spex, because it calculates and saves the factors in a file. Made other changes accordingly.

**Pull request merged**
