### PR TITLE
Update names of extinction files

### PR DESCRIPTION
**Pull request by mdecleir**
The names of the extinction files now contain the name of the comparison star as well.
This makes it easier to try out different comparison stars for a certain reddened star, and plot all the extinction curves for that reddened star in the same plot.

### CODE REVIEW

**Comment by mdecleir** [comment]
I understand why the tests are failing, but I don't understand why some of the tests are not failing!
The test `test_calc_ext.py` should fail, but does not. I will investigate.

**Comment by mdecleir** [comment]
The tests are succeeding locally (on my Mac) because filenames are not case sensitive. Of course, online (on e.g. linux machines) they will fail. I will fix that now.

**Comment by mdecleir** [comment]
All checks have passed! This PR is ready for review!

**Review by karllark — APPROVED** [review]
Looks great.  Nice to see all the assert statements - better testing - yeah!

**Pull request merged**
