### PR TITLE
Indicate HI-lines in the plots

### PR DESCRIPTION
**Pull request by mdecleir**
I added the possibility of indicating the HI-lines in all plots of spectra and extinction curves.

### CODE REVIEW

**Comment by mdecleir** [comment]
The codestyle error is:
`ERROR: InvocationError for command /home/runner/work/measure_extinction/measure_extinction/.tox/codestyle/bin/flake8 measure_extinction --count --max-line-length=100 (exited with code 1)
15`
Not sure how this is possible, because I use Black to make sure the lines are not too long.

**Comment by karllark** [comment]
> The codestyle error is:
> `ERROR: InvocationError for command /home/runner/work/measure_extinction/measure_extinction/.tox/codestyle/bin/flake8 measure_extinction --count --max-line-length=100 (exited with code 1) 15`
> Not sure how this is possible, because I use Black to make sure the lines are not too long.

If you look at the two lines above this one, you can see that there are two codestyle errors.

**Comment by mdecleir** [comment]
> > The codestyle error is:
> > `ERROR: InvocationError for command /home/runner/work/measure_extinction/measure_extinction/.tox/codestyle/bin/flake8 measure_extinction --count --max-line-length=100 (exited with code 1) 15`
> > Not sure how this is possible, because I use Black to make sure the lines are not too long.
> 
> If you look at the two lines above this one, you can see that there are two codestyle errors.

Well, then the error is:
`measure_extinction/plotting/plot_ext.py:143:56: W605 invalid escape sequence '\s'`, which is about this line in the code:
 `table = pd.read_table(path + "HI_lines.list", sep="\s+", comment="#")`.
It complains about the '\s', but that is just the way pandas needs a separator to read tables. So I really don't know how I can fix this code style error.

**Comment by karllark** [comment]
You may be able to solve this by adding an `r` before the double quotes.  E.g., r"\s+".  This says the string is a different type - raw.

**Comment by mdecleir** [comment]
Link_test is failing because it complains about a broken link:
https://ui.adsabs.harvard.edu/abs/2004ApJ...616..912V/abstract
However, I can access the paper through that link...

**Comment by mdecleir** [comment]
And now everything is working...

**Comment by karllark** [comment]
Just a glitch in the testing.  I re-ran the tests.

**Comment by mdecleir** [comment]
> Just a glitch in the testing. I re-ran the tests.

Thanks! I feel like these glitches seem to happen pretty often, at least more than with the Travis testing, or is that just my experience?
In any case, this PR is ready for review.

**Comment by mdecleir** [comment]
> Very neat.
> What about adding the Lyman and Balmer lines as well? That would support this type of plot for FUSE and optical spectra. I'm sure we'd make use of this.
> This comment is mainly motivated hoping it is a small amount of work to do now instead of having to remember how to do this later.

Should be doable in a reasonable time. I'm on it!

**Comment by mdecleir** [comment]
> remember

Done!

**Pull request merged**
